<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.treleas</groupId>
        <artifactId>context-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>context-di-lmbda</artifactId>

    <name>Context DI Lmbda</name>
    <description>Lmbda optimizations for Context DI</description>

    <dependencies>
        <dependency>
            <groupId>net.treleas</groupId>
            <artifactId>context-di</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lanternpowered</groupId>
            <artifactId>lmbda</artifactId>
        </dependency>
        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
        </dependency>
    </dependencies>

</project>